# Generated by Django 3.2.20 on 2023-07-24 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Categories'},
        ),
        migrations.AlterModelOptions(
            name='subcategory',
            options={'verbose_name_plural': 'SubCategories'},
        ),
        migrations.AddField(
            model_name='product',
            name='active_deal',
            field=models.IntegerField(choices=[(0, 'Not visable in Homepage carousel'), (1, 'Visable in Homepage carousel')], default=0),
        ),
    ]
