# Generated by Django 3.2.20 on 2023-07-24 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_auto_20230724_1901'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='specification',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
