# Generated by Django 3.2.20 on 2023-08-03 19:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_icon'),
    ]

    operations = [
        migrations.AddField(
            model_name='icon',
            name='image_url',
            field=models.URLField(blank=True, max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name='icon',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='icons', to='products.product'),
        ),
    ]
