# Generated by Django 3.2.20 on 2023-08-03 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_auto_20230803_1921'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='icon',
            name='product',
        ),
        migrations.AddField(
            model_name='product',
            name='icons',
            field=models.ManyToManyField(blank=True, related_name='icon', to='products.Icon'),
        ),
    ]
